[pytest]

addopts =
    -v
    -p no:cacheprovider

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    ui: UI tests
    api: API tests
    e2e: End-to-end tests
    performance: Performance tests
