environment: "qa"

base_url: "https://practice.expandtesting.com/notes/app"

api_url: "https://practice.expandtesting.com/notes/api"

browser: "chrome"

execution: "remote"

timeout: 20

headless: true

parallel_workers: 3